// accountadmin setup for uploading Snowflake account usage to AWS S3
GRANT EXECUTE TASK ON ACCOUNT TO ROLE TASKADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE TASKADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS SNOWFLAKE_USAGE
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::776377775331:role/MY_SNOWFLAKE_ROLE'
  STORAGE_ALLOWED_LOCATIONS = ('s3://dipaanb-snowflake-usage/');
