// Create Stitch principal and roles
CREATE USER IF NOT EXISTS
  STITCH_SERVICE_ACCOUNT
  PASSWORD = '***'
  MUST_CHANGE_PASSWORD = FALSE;

CREATE ROLE IF NOT EXISTS STITCH_READ_ROLE;
CREATE ROLE IF NOT EXISTS STITCH_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS TASKADMIN;

// Assign Stitch roles
GRANT ROLE STITCH_READ_ROLE        TO ROLE SYSADMIN;
GRANT ROLE STITCH_ADMIN_ROLE       TO ROLE SYSADMIN;
-- GRANT ROLE ACCOUNT_USAGE_READ_ROLE TO ROLE STITCH_ADMIN_ROLE;
GRANT ROLE TASKADMIN               TO ROLE STITCH_ADMIN_ROLE;
GRANT ROLE STITCH_READ_ROLE        TO ROLE STITCH_ADMIN_ROLE;
GRANT ROLE STITCH_ADMIN_ROLE       TO USER STITCH_SERVICE_ACCOUNT;
-- GRANT ROLE SYSADMIN                TO USER STITCH_SERVICE_ACCOUNT;
