// Create Datameer principal and roles
CREATE ROLE IF NOT EXISTS DATAMEER_SERVICE_ROLE;
GRANT ROLE DATAMEER_SERVICE_ROLE   TO ROLE SYSADMIN;
GRANT ROLE TASKADMIN               TO ROLE DATAMEER_SERVICE_ROLE;
GRANT ROLE STITCH_READ_ROLE        TO ROLE DATAMEER_SERVICE_ROLE;

CREATE USER IF NOT EXISTS
  DATAMEER_SERVICE_ACCOUNT
  PASSWORD = '***'
  MUST_CHANGE_PASSWORD = FALSE;

// Assign Datameer roles
GRANT ROLE DATAMEER_SERVICE_ROLE   TO USER DATAMEER_SERVICE_ACCOUNT;
