// grant warehouse usage to admins
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE USERADMIN;

// Create Stitch principal and roles
CREATE USER IF NOT EXISTS
  STITCH_SERVICE_ACCOUNT
  PASSWORD = '***'
  MUST_CHANGE_PASSWORD = FALSE;

CREATE ROLE IF NOT EXISTS STITCH_READ_ROLE;
CREATE ROLE IF NOT EXISTS STITCH_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS TASKADMIN;

// Assign Stitch roles
GRANT ROLE STITCH_READ_ROLE        TO ROLE SYSADMIN;
GRANT ROLE STITCH_ADMIN_ROLE       TO ROLE SYSADMIN;
-- GRANT ROLE ACCOUNT_USAGE_READ_ROLE TO ROLE STITCH_ADMIN_ROLE;
GRANT ROLE TASKADMIN               TO ROLE STITCH_ADMIN_ROLE;
GRANT ROLE STITCH_READ_ROLE        TO ROLE STITCH_ADMIN_ROLE;
GRANT ROLE STITCH_ADMIN_ROLE       TO USER STITCH_SERVICE_ACCOUNT;
-- GRANT ROLE SYSADMIN                TO USER STITCH_SERVICE_ACCOUNT;

// Create Datameer principal and roles
CREATE ROLE IF NOT EXISTS DATAMEER_SERVICE_ROLE;
GRANT ROLE DATAMEER_SERVICE_ROLE   TO ROLE SYSADMIN;
GRANT ROLE TASKADMIN               TO ROLE DATAMEER_SERVICE_ROLE;
GRANT ROLE STITCH_READ_ROLE        TO ROLE DATAMEER_SERVICE_ROLE;
CREATE USER IF NOT EXISTS
  DATAMEER_SERVICE_ACCOUNT
  PASSWORD = '***'
  MUST_CHANGE_PASSWORD = FALSE;

// Assign Datameer roles
GRANT ROLE STITCH_READ_ROLE        TO USER DATAMEER_SERVICE_ACCOUNT;
GRANT ROLE DATAMEER_SERVICE_ROLE   TO USER DATAMEER_SERVICE_ACCOUNT;
