DROP USER IF EXISTS
  STITCH_SERVICE_ACCOUNT;

DROP ROLE IF EXISTS
  STITCH_READ_ROLE;
DROP ROLE IF EXISTS
  STITCH_ADMIN_ROLE;

DROP USER IF EXISTS
  DATAMEER_SERVICE_ACCOUNT;

DROP ROLE IF EXISTS
  DATAMEER_SERVICE_ROLE;
