// Set Stitch service account defaults
ALTER USER
  STITCH_SERVICE_ACCOUNT
SET
  DEFAULT_ROLE=STITCH_ADMIN_ROLE
  DEFAULT_WAREHOUSE=STITCH_INGESTION_WH;

// Grant read permissions to Stitch
GRANT USAGE ON DATABASE STITCH_DB                         TO ROLE STITCH_READ_ROLE;
GRANT USAGE ON SCHEMA STITCH_DB.PUBLIC                    TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA STITCH_DB.PUBLIC     TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA STITCH_DB.PUBLIC      TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STITCH_DB.PUBLIC  TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STITCH_DB.PUBLIC   TO ROLE STITCH_READ_ROLE;

GRANT USAGE ON SCHEMA STITCH_DB.STAGE_1                   TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA STITCH_DB.STAGE_1    TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA STITCH_DB.STAGE_1     TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STITCH_DB.STAGE_1 TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STITCH_DB.STAGE_1  TO ROLE STITCH_READ_ROLE;

GRANT USAGE ON SCHEMA STITCH_DB.STAGE_2                   TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA STITCH_DB.STAGE_2    TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA STITCH_DB.STAGE_2     TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STITCH_DB.STAGE_2 TO ROLE STITCH_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STITCH_DB.STAGE_2  TO ROLE STITCH_READ_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA STITCH_DB.STAGE_2         TO ROLE STITCH_READ_ROLE;

GRANT USAGE ON WAREHOUSE STITCH_INGESTION_WH              TO ROLE STITCH_READ_ROLE;

// Grant admin permissions
GRANT USAGE ON INTEGRATION SNOWFLAKE_USAGE                TO ROLE STITCH_ADMIN_ROLE;

GRANT CREATE TABLE ON SCHEMA STITCH_DB.STAGE_1            TO ROLE STITCH_ADMIN_ROLE;
GRANT CREATE STAGE ON SCHEMA STITCH_DB.STAGE_1            TO ROLE STITCH_ADMIN_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA STITCH_DB.STAGE_1      TO ROLE STITCH_ADMIN_ROLE;
GRANT CREATE TASK ON SCHEMA STITCH_DB.STAGE_1             TO ROLE STITCH_ADMIN_ROLE;

GRANT CREATE TABLE ON SCHEMA STITCH_DB.STAGE_2            TO ROLE STITCH_ADMIN_ROLE;
GRANT CREATE STAGE ON SCHEMA STITCH_DB.STAGE_2            TO ROLE STITCH_ADMIN_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA STITCH_DB.STAGE_2      TO ROLE STITCH_ADMIN_ROLE;

GRANT USAGE, OPERATE ON WAREHOUSE STITCH_INGESTION_WH     TO ROLE STITCH_ADMIN_ROLE;
