USE SCHEMA STITCH_DB.STAGE_1;

DROP FILE FORMAT QUERY_HISTORY_CSV_FORMAT;
DROP STAGE QUERY_HISTORY_STAGE;

CREATE OR REPLACE FILE FORMAT QUERY_HISTORY_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  FIELD_DELIMITER = '|'
  COMPRESSION = NONE;

CREATE STAGE QUERY_HISTORY_STAGE
  STORAGE_INTEGRATION = SNOWFLAKE_USAGE
  URL = 's3://dipaanb-snowflake-usage/query_history'
  FILE_FORMAT = QUERY_HISTORY_CSV_FORMAT;
