USE SCHEMA STITCH_DB.STAGE_1;

DROP FILE FORMAT IF EXISTS TASK_HISTORY_CSV_FORMAT;
DROP STAGE IF EXISTS TASK_HISTORY_STAGE;

DROP FILE FORMAT IF EXISTS TASKS_CSV_FORMAT;
DROP STAGE IF EXISTS TASKS_STAGE;

CREATE OR REPLACE FILE FORMAT TASKS_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  FIELD_DELIMITER = '|'
  COMPRESSION = NONE;

CREATE STAGE TASKS_STAGE
  STORAGE_INTEGRATION = SNOWFLAKE_USAGE
  URL = 's3://dipaanb-snowflake-usage/tasks'
  FILE_FORMAT = TASKS_CSV_FORMAT;

DROP FILE FORMAT IF EXISTS TASK_USAGE_HISTORY_CSV_FORMAT;
DROP STAGE IF EXISTS TASK_USAGE_HISTORY_STAGE;

CREATE OR REPLACE FILE FORMAT TASK_USAGE_HISTORY_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  FIELD_DELIMITER = '|'
  COMPRESSION = NONE;

CREATE STAGE TASK_USAGE_HISTORY_STAGE
  STORAGE_INTEGRATION = SNOWFLAKE_USAGE
  URL = 's3://dipaanb-snowflake-usage/task_usage_history'
  FILE_FORMAT = TASK_USAGE_HISTORY_CSV_FORMAT;
