USE SCHEMA STITCH_DB.STAGE_1;

DROP FILE FORMAT WAREHOUSE_METERING_HISTORY_CSV_FORMAT;
DROP STAGE WAREHOUSE_METERING_HISTORY_STAGE;

CREATE OR REPLACE FILE FORMAT WAREHOUSE_METERING_HISTORY_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  FIELD_DELIMITER = '|'
  COMPRESSION = NONE;

CREATE STAGE WAREHOUSE_METERING_HISTORY_STAGE
  STORAGE_INTEGRATION = SNOWFLAKE_USAGE
  URL = 's3://dipaanb-snowflake-usage/warehouse_metering_history'
  FILE_FORMAT = WAREHOUSE_METERING_HISTORY_CSV_FORMAT;
